// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1) {
  return window['go']['main']['App']['Base64Decode'](arg1);
}

export function Base64Encode(arg1) {
  return window['go']['main']['App']['Base64Encode'](arg1);
}

export function CSSFormat(arg1) {
  return window['go']['main']['App']['CSSFormat'](arg1);
}

export function CSSMinify(arg1) {
  return window['go']['main']['App']['CSSMinify'](arg1);
}

export function ConvertBase(arg1, arg2) {
  return window['go']['main']['App']['ConvertBase'](arg1, arg2);
}

export function GeneratePassword(arg1) {
  return window['go']['main']['App']['GeneratePassword'](arg1);
}

export function GenerateUUID() {
  return window['go']['main']['App']['GenerateUUID']();
}

export function GenerateUUIDs(arg1) {
  return window['go']['main']['App']['GenerateUUIDs'](arg1);
}

export function HTMLFormat(arg1) {
  return window['go']['main']['App']['HTMLFormat'](arg1);
}

export function HexToColor(arg1) {
  return window['go']['main']['App']['HexToColor'](arg1);
}

export function JSONFormat(arg1, arg2) {
  return window['go']['main']['App']['JSONFormat'](arg1, arg2);
}

export function JSONMinify(arg1) {
  return window['go']['main']['App']['JSONMinify'](arg1);
}

export function JWTDecode(arg1) {
  return window['go']['main']['App']['JWTDecode'](arg1);
}

export function JWTEncode(arg1, arg2, arg3) {
  return window['go']['main']['App']['JWTEncode'](arg1, arg2, arg3);
}

export function NowTime() {
  return window['go']['main']['App']['NowTime']();
}

export function PasswordStrength(arg1) {
  return window['go']['main']['App']['PasswordStrength'](arg1);
}

export function RegexExplain(arg1) {
  return window['go']['main']['App']['RegexExplain'](arg1);
}

export function RegexTest(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegexTest'](arg1, arg2, arg3);
}

export function SQLFormat(arg1) {
  return window['go']['main']['App']['SQLFormat'](arg1);
}

export function TextAnalyze(arg1) {
  return window['go']['main']['App']['TextAnalyze'](arg1);
}

export function TextDiff(arg1, arg2) {
  return window['go']['main']['App']['TextDiff'](arg1, arg2);
}

export function TextTransform(arg1, arg2) {
  return window['go']['main']['App']['TextTransform'](arg1, arg2);
}

export function URLDecode(arg1) {
  return window['go']['main']['App']['URLDecode'](arg1);
}

export function URLEncode(arg1) {
  return window['go']['main']['App']['URLEncode'](arg1);
}

export function UnixToTime(arg1) {
  return window['go']['main']['App']['UnixToTime'](arg1);
}

export function ValidateUUID(arg1) {
  return window['go']['main']['App']['ValidateUUID'](arg1);
}

export function XMLFormat(arg1) {
  return window['go']['main']['App']['XMLFormat'](arg1);
}
