// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Base64Decode(arg1:string):Promise<string>;

export function Base64Encode(arg1:string):Promise<string>;

export function CSSFormat(arg1:string):Promise<string>;

export function CSSMinify(arg1:string):Promise<string>;

export function ConvertBase(arg1:string,arg2:number):Promise<main.BaseResult>;

export function GeneratePassword(arg1:main.PasswordOptions):Promise<string>;

export function GenerateUUID():Promise<string>;

export function GenerateUUIDs(arg1:number):Promise<Array<string>>;

export function HTMLFormat(arg1:string):Promise<string>;

export function HexToColor(arg1:string):Promise<main.ColorResult>;

export function JSONFormat(arg1:string,arg2:number):Promise<main.JSONResult>;

export function JSONMinify(arg1:string):Promise<main.JSONResult>;

export function JWTDecode(arg1:string):Promise<main.JWTResult>;

export function JWTEncode(arg1:string,arg2:string,arg3:string):Promise<string>;

export function NowTime():Promise<main.TimeResult>;

export function PasswordStrength(arg1:string):Promise<Record<string, any>>;

export function RegexExplain(arg1:string):Promise<string>;

export function RegexTest(arg1:string,arg2:string,arg3:string):Promise<main.RegexResult>;

export function SQLFormat(arg1:string):Promise<string>;

export function TextAnalyze(arg1:string):Promise<main.TextStats>;

export function TextDiff(arg1:string,arg2:string):Promise<Array<main.DiffLine>>;

export function TextTransform(arg1:string,arg2:string):Promise<string>;

export function URLDecode(arg1:string):Promise<string>;

export function URLEncode(arg1:string):Promise<string>;

export function UnixToTime(arg1:number):Promise<main.TimeResult>;

export function ValidateUUID(arg1:string):Promise<boolean>;

export function XMLFormat(arg1:string):Promise<string>;
